services:
  stump:
    image: aaronleopold/stump:latest
    container_name: stump
    volumes:
      - /home/eyes/docker/stump:/config
      - /home/eyes/media/comics:/data
    ports:
      - 10801:10801
    environment:
      - PUID=1000
      - PGID=1000
    #      - STUMP_CONFIG_DIR=/mnt/stump/config
    restart: unless-stopped
    networks:
      - net

networks:
  net:
    external: true
    name: net
