services:
  app:
    image: "docker.io/jc21/nginx-proxy-manager:latest"
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /home/eyes/docker/nginxproxymanager/data:/data
      - /home/eyes/docker/nginxproxymanager/letsencrypt:/etc/letsencrypt
    networks:
      - proxy

  vaultwarden:
    image: "vaultwarden/server:latest"
    container_name: vaultwarden
    ports:
      - "8666:80"
    restart: unless-stopped
    volumes:
      - "/home/eyes/docker/vaultwarden/data/:/data/"
    networks:
      - proxy

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8888:8080"
    volumes:
      - /home/eyes/docker/searxng/config:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8888
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - proxy

networks:
  proxy:
    driver: bridge

