services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: Server
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/eyes/docker/syncthing:/var/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    networks:
      - net

networks:
  net:
    external: true
    name: net
