services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - "9999:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/eyes/docker/stash/config:/root/.stash
      - /home/eyes/media/stash:/data
      - /home/eyes/docker/stash/metadata:/metadata
      - /home/eyes/docker/stash/cache:/cache
      - /home/eyes/docker/stash/blobs:/blobs
      - /home/eyes/docker/stash/generated:/generated

    networks:
      - net

networks:
  net:
    external: true
    name: net
