services:
  umbrel:
    image: dockurr/umbrel
    container_name: umbrel
    pid: host
    ports:
      - 8060:80
    volumes:
      - "/home/eyes/docker/umbrel:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    stop_grace_period: 1m
