services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - /home/eyes/docker/linkwarden/pgdata:/var/lib/postgresql/data
    networks:
      - net

  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    image: ghcr.io/linkwarden/linkwarden:latest
    ports:
      - 3000:3000
    volumes:
      - /home/eyes/docker/linkwarden/data:/data/data
    depends_on:
      - postgres
    networks:
      - net

networks:
  net:
    external: true
    name: net
